import requests
import json
from typing import Optional, List, Dict, Any
from ..config import get_settings

settings = get_settings()

class LLMService:
    def __init__(self):
        self.openrouter_key = settings.OPENROUTER_API_KEY
        self.groq_key = settings.GROQ_API_KEY
        self.openrouter_url = "https://openrouter.ai/api/v1/chat/completions"
        self.groq_url = "https://api.groq.com/openai/v1/chat/completions"
        self.groq_model = (settings.GROQ_MODEL or "llama-3.3-70b-versatile").strip()
        self.model_id = "openai/gpt-oss-120b:free"
        self.llm_mode = (settings.LLM_MODE or "auto").strip().lower()
        if self.llm_mode not in {"auto", "online", "offline"}:
            self.llm_mode = "auto"

    def get_mode(self) -> str:
        return self.llm_mode

    def set_mode(self, mode: str) -> str:
        normalized = (mode or "auto").strip().lower()
        if normalized not in {"auto", "online", "offline"}:
            normalized = "auto"
        self.llm_mode = normalized
        settings.LLM_MODE = normalized
        return self.llm_mode

    async def generate_with_reasoning(self, messages: List[Dict[str, Any]], mode: str = "auto") -> Dict[str, Any]:
        """
        Generates a response using Groq by default when configured.
        mode: 'auto', 'groq', or 'openrouter'
        """
        if self.llm_mode == "offline":
            return self._offline_response(messages)

        use_groq = False
        if mode in {"groq", "gemini"}:
            # keep "gemini" alias for backward compatibility with existing callers.
            use_groq = True
        elif mode == "openrouter":
            use_groq = False
        elif self.llm_mode == "online":
            use_groq = bool(self.groq_key)
        else:
            use_groq = bool(self.groq_key)
            
        if use_groq and self.groq_key:
            return await self._generate_groq(messages)
        else:
            return await self._generate_openrouter(messages)

    async def _generate_groq(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        headers = {
            "Authorization": f"Bearer {self.groq_key}",
            "Content-Type": "application/json",
        }
        data = {
            "model": self.groq_model,
            "messages": messages,
            "temperature": 0.3,
        }
        try:
            response = requests.post(self.groq_url, headers=headers, json=data, timeout=20)
            response.raise_for_status()
            res_json = response.json()
            content = res_json.get("choices", [{}])[0].get("message", {}).get("content", "")
            return {
                "content": content,
                "reasoning_details": (
                    f"Response generated by Groq {self.groq_model}. "
                    "Dynamic benefit analysis complete."
                )
            }
        except Exception as e:
            latest = messages[-1].get("content", "") if messages else ""
            return self._get_fallback(f"Groq Error: {e}", latest)

    async def _generate_openrouter(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        if not self.openrouter_key:
            latest = messages[-1].get("content", "") if messages else ""
            return self._get_fallback("OpenRouter key missing", latest)

        headers = {
            "Authorization": f"Bearer {self.openrouter_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://bharat-benefits.navigator",
            "X-Title": "Bharat Benefits Navigator"
        }
        data = {
            "model": self.model_id,
            "messages": messages,
            "reasoning": {"enabled": True}
        }
        try:
            response = requests.post(self.openrouter_url, headers=headers, data=json.dumps(data), timeout=10)
            response.raise_for_status()
            res_json = response.json()
            message = res_json['choices'][0]['message']
            return {
                "content": message.get('content'),
                "reasoning_details": message.get('reasoning_details') or "GPT-OSS-120B reasoning complete."
            }
        except Exception as e:
            latest = messages[-1].get("content", "") if messages else ""
            return self._get_fallback(f"OpenRouter Error: {e}", latest)

    def _infer_lang(self, text: str) -> str:
        sample = (text or "").strip()
        if any("\u0C00" <= ch <= "\u0C7F" for ch in sample):
            return "te"
        if any("\u0B80" <= ch <= "\u0BFF" for ch in sample):
            return "ta"
        if any("\u0900" <= ch <= "\u097F" for ch in sample):
            return "hi"
        lower = sample.lower()
        if any(token in lower for token in ["mera", "mujhe", "kripya", "namaste"]):
            return "hi"
        if any(token in lower for token in ["nenu", "naaku", "dayachesi", "namaskaram"]):
            return "te"
        if any(token in lower for token in ["naan", "enakku", "vanakkam"]):
            return "ta"
        return "en"

    def _localized_fallback(self, lang: str) -> str:
        if lang == "te":
            return (
                "మీ ప్రొఫైల్ ఆధారంగా మీరు కొన్ని ప్రభుత్వ పథకాలకు అర్హులు కావచ్చు. "
                "ఆధార్, ఆదాయ ధృవీకరణ పత్రాలు సిద్ధంగా ఉంచి తదుపరి దశలను కొనసాగించండి."
            )
        if lang == "ta":
            return (
                "உங்கள் சுயவிவரத்தின் அடிப்படையில் சில அரசுத் திட்டங்களுக்கு நீங்கள் தகுதியானவராக இருக்கலாம். "
                "ஆதார் மற்றும் வருமான ஆவணங்களை தயார் வைத்து அடுத்த படிகளை தொடருங்கள்."
            )
        if lang == "hi":
            return (
                "आपकी प्रोफ़ाइल के आधार पर आप कुछ सरकारी योजनाओं के लिए पात्र हो सकते हैं। "
                "कृपया आधार और आय प्रमाण पत्र तैयार रखें और अगले चरण पूरे करें।"
            )
        return (
            "Based on your profile, you may be eligible for several government schemes. "
            "Please keep Aadhaar and income documents ready and continue with next steps."
        )

    def _get_fallback(self, error_msg: str, latest_prompt: str = "") -> Dict[str, Any]:
        print(f"LLMService Fallback: {error_msg}")
        lang = self._infer_lang(latest_prompt)
        return {
            "content": self._localized_fallback(lang),
            "reasoning_details": f"Note: AI is in fallback mode ({error_msg[:20]}...). Matching pre-indexed profile data."
        }

    def _offline_response(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        latest = ""
        if messages:
            latest = str(messages[-1].get("content", "")).strip()
        if latest:
            summary = (
                "Offline mode is active. Here is a local rule-based explanation: "
                "you may qualify based on your profile and scheme criteria. "
                "Review required documents and submit details carefully."
            )
        else:
            summary = (
                "Offline mode is active. Local rules are being used to explain scheme eligibility."
            )
        return {
            "content": summary,
            "reasoning_details": "LLM_MODE=offline. No external API calls were made."
        }

    async def generate_text(self, prompt: str) -> str:
        messages = [{"role": "user", "content": prompt}]
        result = await self.generate_with_reasoning(messages)
        return result["content"]

# Singleton
llm_service = LLMService()
